package kun.kuntv_backend.enums;

public enum TagSezione {
    DOCUMENTARIO, DRAMMATICO, SATIRA, BLACK_COMEDY, FANTASCIENZA, AVVENTURA, FANTASY, POLIZIESCO, THRILLER, PSICOLOGICO, GIALLO, AZIONE, COMMEDIA
}
